### PR TITLE
Issue #2 hotfix

### LINKED ISSUE #2: Alpha bar doesn't update when a colour is typed into the input box
@DavidRGriswold

When you type in a colour into the input box, the colour palette and the hue bar get updated. But the alpha bar doesn't update.

This is what happens when I type "blue" into the box:

image

### PR DESCRIPTION
**Pull request by DavidRGriswold**
Fixes #2 (also re-minified)

### CODE REVIEW

**Comment by DavidRGriswold** [comment]
wait, something isn't right. Closing and trying again.

**Comment by DavidRGriswold** [comment]
Why is this saying it's trying to merge all 24-something commits? I really don't understand some aspects of this process. Anyway. This should be ready for review.

**Comment by daattali** [comment]
Did you do a git pull before submitting?

**Comment by DavidRGriswold** [comment]
I did a git fetch then a git merge from your project. Was following an
online tutorial for syncing a fork to the original remote repository.

Anyway, sorry if this was wrong. Still wrapping my brain around it all.

**Comment by daattali** [comment]
I saw that this fix is a one liner so to keep the git history organized, I added it in a separate minimal commit https://github.com/daattali/jquery-colourpicker/commit/857af561d3f63a8ab9cdb21c116793dc981fffd4

I mentioned you in the commit message

I hope you don't mind

**Comment by DavidRGriswold** [comment]
No problem

**Pull request closed without merging**
